// Lexical grammar

%lex

%%

\s+                         /* skip whitespaces */
\d+(\.\d+)?                  return 'NUMBER'
\"[^\"]*\"                  return 'STRING'
[\w\-*+/<>=]+                return 'SYMBOL'

/lex

// Syntax grammar

%%

Exp
    : Atom
    | List
    ;

Atom
    : NUMBER     { $$ = Number($1) }
    | STRING
    | SYMBOL
    ;

List
    : '(' ListEntries ')'       { $$ = $2 }
    ;

ListEntries
    : ListEntries Exp   { $1.push($2); $$ = $1 }
    | /* empty */       { $$ = [] }
    ;